spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.example.entity
  config-location: classpath:mybatis-config.xml


